FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    docker.io \
    docker-cli \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*

# Add jenkins user to docker and root groups so it has permission to access the Docker socket
RUN usermod -aG docker,root jenkins

USER jenkins